# Generated by Django 2.1.1 on 2018-09-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='premium_tier',
            field=models.IntegerField(default=0),
        ),
    ]
