# Generated by Django 2.1.1 on 2018-09-17 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20180917_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='bumped_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
