# Generated by Django 2.1.1 on 2018-09-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20180917_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servercategory',
            name='servers',
            field=models.ManyToManyField(blank=True, related_name='categories', to='servers.DiscordServer'),
        ),
        migrations.AlterField(
            model_name='servertag',
            name='servers',
            field=models.ManyToManyField(blank=True, related_name='tags', to='servers.DiscordServer'),
        ),
    ]
