# Generated by Django 2.1.1 on 2018-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20180917_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servercategory',
            name='servers',
        ),
        migrations.RemoveField(
            model_name='servertag',
            name='servers',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='tags',
            field=models.ManyToManyField(related_name='servers', to='servers.ServerTag'),
        ),
    ]
