# Generated by Django 2.1.1 on 2018-09-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20180917_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerCategory',
        ),
    ]
