# Generated by Django 2.1.1 on 2018-09-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_auto_20180919_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordserver',
            old_name='premium_from',
            new_name='premium_1_from',
        ),
        migrations.RenameField(
            model_name='discordserver',
            old_name='premium_until',
            new_name='premium_1_until',
        ),
        migrations.AddField(
            model_name='discordserver',
            name='premium_2_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discordserver',
            name='premium_2_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
