# Generated by Django 2.1.1 on 2018-09-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_auto_20180919_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servertag',
            old_name='tag',
            new_name='name',
        ),
    ]
