# Generated by Django 2.1.1 on 2018-09-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_auto_20180919_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='servermanager',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='servers.DiscordServer'),
        ),
    ]
