# Generated by Django 2.1.1 on 2018-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_auto_20180920_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='premium_highlight',
            field=models.IntegerField(choices=[(0, 'Blue Grey - Default'), (1, 'Yellow - Premium Tier 1 + 2'), (2, 'Pink - Premium Tier 1 + 2'), (3, 'Red - Premium Tier 2')], default=0),
        ),
    ]
