# Generated by Django 2.1.1 on 2018-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_auto_20180921_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordemoji',
            name='animated',
            field=models.BooleanField(default=False),
        ),
    ]
