# Generated by Django 2.1.1 on 2018-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveawayinformation',
            name='description',
            field=models.TextField(blank=True, help_text='Edit as you want, or use Code View to edit in HTML.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='giveawayinformation',
            name='ended',
            field=models.BooleanField(default=False, help_text='Check this to mark the Giveaway as ended. It will not show in the page.'),
        ),
        migrations.AlterField(
            model_name='giveawayinformation',
            name='title',
            field=models.CharField(blank=True, help_text='A title that does not show in the page. Only in the Admin interface.', max_length=200),
        ),
    ]
