# Generated by Django 2.1.1 on 2018-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('url', models.CharField(max_length=256)),
                ('image', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
