# Generated by Django 2.1.1 on 2018-10-09 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnersinformation',
            old_name='image',
            new_name='image_url',
        ),
    ]
