# Generated by Django 2.1.1 on 2018-10-02 02:10

from django.db import migrations, models
import django.utils.timezone
import web.apps.partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersinformation',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=web.apps.partners.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
