# Generated by Django 2.1.1 on 2018-10-02 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersinformation',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
