# Generated by Django 2.1.1 on 2018-10-09 02:39

from django.db import migrations, models
import web.apps.partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20181009_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersinformation',
            name='image_url',
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=web.apps.partners.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='partnersinformation',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
