# Generated by Django 2.1.1 on 2018-09-17 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20180917_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='bumped_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 17, 8, 31, 1, 461958, tzinfo=utc), null=True),
        ),
    ]
