# Generated by Django 2.1.1 on 2018-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_auto_20180917_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='servers', to='servers.ServerTag'),
        ),
    ]
