# Generated by Django 2.1.1 on 2018-09-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumfeature',
            name='icon_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='premiumfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
