# Generated by Django 2.1.1 on 2018-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiums', '0002_auto_20180920_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumfeature',
            name='background_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumfeature',
            name='icon_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
