# Generated by Django 2.1.1 on 2018-09-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premiums', '0003_auto_20180920_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumfeature',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
